version: "3.7"
services:
  app:
    build:
      context: ./backend-laravel
      dockerfile: Dockerfile
    image: insamo-backend
    container_name: insamo-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend-laravel:/var/www
    networks:
      - insamo-network

  db:
    image: mysql:8.0
    container_name: insamo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-insamo_rw}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-insamo}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - insamo-network

  nginx:
    image: nginx:alpine
    container_name: insamo-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend-laravel:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - insamo-network
    depends_on:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: insamo-frontend
    container_name: insamo-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - insamo-network
    depends_on:
      - app

networks:
  insamo-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
