version: "3.7"
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: insamo-backend:prod
    container_name: insamo-backend-prod
    restart: unless-stopped
    working_dir: /var/www
    environment:
      APP_ENV: production
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_KEY: ${APP_KEY}
      FRONTEND_URL: ${FRONTEND_URL:-http://app.insamo.id}
      APP_URL: ${APP_URL:-http://apiapp.insamo.id}
    command: >
      sh -c "mkdir -p /var/www/storage/logs && touch /var/www/storage/logs/laravel.log && chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache && chmod -R 775 /var/www/storage /var/www/bootstrap/cache && php-fpm"
    volumes:
      - ./backend/storage:/var/www/storage
    networks:
      - insamo-prod-network
      - web

  db:
    image: mysql:8.0
    container_name: insamo-db-prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-insamo_rw}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - dbdata-prod:/var/lib/mysql
    networks:
      - insamo-prod-network

  nginx:
    image: nginx:alpine
    container_name: insamo-nginx-prod
    restart: unless-stopped
    # Ports dihapus karena diakses via network 'web' oleh Nginx Server
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - insamo-prod-network
      - web
    depends_on:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: insamo-frontend:prod
    container_name: insamo-frontend-prod
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://apiapp.insamo.id/api
    # Ports dihapus karena diakses via network 'web' oleh Nginx Server
    networks:
      - insamo-prod-network
      - web

networks:
  insamo-prod-network:
    driver: bridge
  web:
    external: true

volumes:
  dbdata-prod:
    driver: local
