name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd ~/Insamo
            git pull origin main

            # Setup environment file if not exists
            if [ ! -f .env ]; then
              cp .env.example .env
            fi

            docker compose down

            # Restart containers
            docker compose -f docker-compose.prod.yml up -d --build
            docker compose -f docker-compose.prod.yml exec -T app php artisan jwt:secret
            docker compose -f docker-compose.prod.yml exec -T app php artisan migrate --force 

            # Cleanup and optimization
            docker compose -f docker-compose.prod.yml exec -T app rm -rf /var/www/storage/framework/views/*
            docker compose -f docker-compose.prod.yml exec -T app php artisan view:clear
            docker compose -f docker-compose.prod.yml exec -T app php artisan config:clear
            docker compose -f docker-compose.prod.yml exec -T app php artisan cache:clear

            # Database migration
            

            # Optional: Clear other caches
            docker compose -f docker-compose.prod.yml exec -T app php artisan config:cache
            docker compose -f docker-compose.prod.yml exec -T app php artisan view:cache
            docker compose -f docker-compose.prod.yml exec -T app php artisan storage:link
            docker restart $(docker ps -q)
            
